### ISSUE TITLE
Only run imputation?

### ISSUE THREAD

**Issue by cnk113** [YiliangTracyZhang/SCRIBE#1]
Hello,

I've read your manuscript, and I noticed it corrected and imputed simultaneously.
I was wondering if the code and model can only run imputation?
Like would it be fine to just pass in one dataset?

Thanks,
Chang

**Comment by YiliangTracyZhang** [comment]
Hi Kim,

Thank you for your email and yes, it can.
If there is only one batch, you can provide the program with the batch
index (1, 1, ....., 1). That means all the cells are in the same batch.
Best,
Yiliang
